version: '3.8'

services:
  web:
    build: .
    container_name: cocktail_advisor_chat
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped

